os: osx
language: objective-c
osx_image: xcode9.1

before_install:
  - env
  - locale
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail
  - xcodebuild clean build -scheme FontSizeInspector -sdk iphonesimulator -configuration Debug | xcpretty -c
  